# Generated by Django 4.1.5 on 2023-02-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_dtr',
            name='subject',
        ),
    ]
