# Generated by Django 4.1.5 on 2023-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employee_dtr_weekday_alter_employee_dtr_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dtr',
            name='total_working_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
