# Generated by Django 4.1.5 on 2023-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_status',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
