# Generated by Django 4.1.5 on 2023-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_employee_dtr_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='VACANT', max_length=20),
        ),
    ]
