# Generated by Django 4.1.5 on 2023-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_employee_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
