# Generated by Django 4.1.5 on 2023-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_schedule_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
