# Generated by Django 4.1.5 on 2023-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dtr',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
