# Generated by Django 4.1.5 on 2023-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_dtr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
