# Generated by Django 4.1.5 on 2023-02-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_employee_dtr_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dtr',
            name='weekday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_dtr',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='attendance.employee'),
        ),
    ]
