# Generated by Django 4.1.5 on 2023-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employee_dtr_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_dtr',
            name='time_in',
            field=models.DateTimeField(),
        ),
    ]
