# Generated by Django 4.1.5 on 2023-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_schedule_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_status',
            options={'verbose_name': 'Employee Status', 'verbose_name_plural': 'Employee Statuses'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
