# Generated by Django 4.1.5 on 2023-04-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_employee_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_dtr',
            options={'verbose_name': 'Employee DTR', 'verbose_name_plural': 'Employee DTRs'},
        ),
        migrations.AlterModelOptions(
            name='employee_position',
            options={'verbose_name': 'Employee Position', 'verbose_name_plural': 'Employee Positions'},
        ),
    ]
