# Generated by Django 4.1.5 on 2023-04-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dtr',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='VACANT', max_length=20),
        ),
    ]
