# Generated by Django 4.1.5 on 2023-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_employee_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
