# Generated by Django 4.1.5 on 2023-04-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0028_employee_absence_records"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee_Absence_Records", new_name="Employee_Absence_Record",
        ),
    ]
