# Generated by Django 4.1.5 on 2023-04-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_rename_employee_absence_records_employee_absence_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
