# Generated by Django 4.1.5 on 2023-04-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time_in']},
        ),
    ]
